# Generated by Django 4.2.4 on 2023-09-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_shoppingcartrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_cart', to='recipes.recipe'),
        ),
    ]
